spring:
  #profiles: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}

jpa:
  hibernate:
  ddl-auto: update
  database-platform: org.hibernate.dialect.PostgreSQLDialect
